#pragma once
#define YUM_ENGINE_VERSION_MAJOR 2
#define YUM_ENGINE_VERSION_MINOR 0
#define YUM_ENGINE_VERSION_PATCH 2
#define YUM_ENGINE_VERSION_INT ((2*10000)+(0*100)+(2))
#define YUM_ENGINE_VERSION_BRANCH "stable"
#define YUM_ENGINE_VERSION_STUDIO "yum-official"
#define _YUM_DEF_VERSION(MAJ, MIN, PAT) (((MAJ) * 10000) + ((MIN) * 100) + (PAT))
