#pragma once
#define YUM_ENGINE_VERSION_MAJOR 2
#define YUM_ENGINE_VERSION_MINOR 3
#define YUM_ENGINE_VERSION_PATCH 32
#define YUM_ENGINE_VERSION_INT ((2*10000)+(3*100)+(32))
#define YUM_ENGINE_VERSION_BRANCH "stable"
#define YUM_ENGINE_VERSION_STUDIO "yum-official"
#define _YUM_DEF_VERSION(MAJ, MIN, PAT) (((MAJ) * 10000) + ((MIN) * 100) + (PAT))
