#pragma once
#define YUM_ENGINE_VERSION_MAJOR 1
#define YUM_ENGINE_VERSION_MINOR 8
#define YUM_ENGINE_VERSION_PATCH 28
#define YUM_ENGINE_VERSION_INT ((1*10000)+(8*100)+(28))
#define YUM_ENGINE_VERSION_BRANCH "stable"
#define YUM_ENGINE_VERSION_STUDIO "yum-official"
#define _YUM_DEF_VERSION(MAJ, MIN, PAT) (((MAJ) * 10000) + ((MIN) * 100) + (PAT))
