#ifndef YUM_ENGINE_INCLUDE_GUARD
#define YUM_ENGINE_INCLUDE_GUARD
#define YUM_ENGINE_VERSION_MAJOR 3
#define YUM_ENGINE_VERSION_MINOR 4
#define YUM_ENGINE_VERSION_PATCH 0
#define YUM_ENGINE_VERSION_INT ((3*10000)+(4*100)+(0))
#define YUM_ENGINE_VERSION_BRANCH "master-stable"
#define YUM_ENGINE_VERSION_STUDIO "yum-official"
#endif